DATAAUG:
    RAND_SCALE_MIN: 0.5
    RAND_SCALE_MAX: 2.0
    BASE_SIZE: 1024
    CROP_SIZE: 768
    EXTRA: True
TRAIN_BATCH_SIZE: 8
TRAIN_BATCH_SIZE_PER_GPU: 4
VAL_BATCH_SIZE: 4
NUM_TRAINERS: 4
EVAL_BATCH_SIZE: 1
DATASET:
    DATASET_NAME: "cityscapes"
    DATA_DIR: "./data/cityscapes/"
    DATA_ROOT: "./data"
    IMAGE_TYPE: "rgb"  # choice rgb or rgba
    NUM_CLASSES: 19
    TEST_FILE_LIST: "./data/cityscapes/cityscapes_list/test.lst"
    TRAIN_FILE_LIST: "./data/cityscapes/cityscapes_list/train.lst"
    VAL_FILE_LIST: "./data/cityscapes/cityscapes_list/val.lst"
    IGNORE_INDEX: 255
    DATA_DIM: 3
MODEL:
    MODEL_NAME: "glore"
    DEFAULT_NORM_TYPE: "bn"
    MULTI_LOSS_WEIGHT: [1.0, 0.4]
    BACKBONE: "resnet"
    BACKBONE_LAYERS: 101
    BACKBONE_MULTI_GRID: False
    PSPNET:
        DEPTH_MULTIPLIER: 1
        AuxHead: True
TRAIN:
    PRETRAINED_MODEL_FILE: "./pretrained_model/resnet101_pretrained.pdparams"
    MODEL_SAVE_DIR:  "snapshots/glore_res101_cityscapes/"
    MODEL_SAVE_LAST: "snapshots/glore_res101_cityscapes/glore_res101_cityscapes_last"
    MODEL_SAVE_BEST: "snapshots/glore_res101_cityscapes/glore_res101_cityscapes_best"
    SNAPSHOT_EPOCH: 1
TEST:
    TEST_MODEL_FILE: "snapshots/glore_res101_cityscapes/glore_res101_cityscapes_best.pdparams"
    BASE_SIZE: 2048
    CROP_SIZE: 1024
    SLIDE_WINDOW: True
    MULTI_SCALE: False
    FLIP: True
    OUTPUT_PATH: "output"
SOLVER:
    LR: 0.01
    POWER: 0.9
    WEIGHT_DECAY: 0.0001
    LR_POLICY: "poly"
    OPTIMIZER: "sgd"
    NUM_EPOCHS: 80
    LOSS: "['softmax_loss']"


